[google_ads]
developer_token = "your_google_ads_dev_token"
client_id = "your_oauth_client_id"
client_secret = "your_oauth_client_secret"
refresh_token = "your_refresh_token"
login_customer_id = "your_google_ads_manager_id"
